---
stages: [maven, test, sonar, docker, deploy]

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/webapp"

maven_build:
  stage: maven
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn -q -DskipTests clean package
  artifacts:
    paths:
      - target/*.jar

unittest:
  stage: test
  image:
  script:
    - mvn -q test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml

sonarscan:
  stage: sonar
  image: maven:3.9-eclipse-temurin-17
  script: 
    - mvn -q verify sonar:sonar
    - Dsonar.login=$SONAR_TOKEN
    - Dsonar.host.url=$SONAR_HOST_URL
  dependencies:
    - maven_build
  rules:
    - if: $SONAR_TOKEN

dockerbuildpush:
  stage: docker
  image: docker25.0.3
  services: [docker: 25.0.3-dind]
  variables:
          DOCKER_DRIVER: overlay
  before_script:
    - |
      if [ -n "$DOCKER_USER" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        export DOCKER_IMAGE=${DOCKER_IMAGE:-"poori123321/webapp"}
      else
        echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
      fi
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  dependencies:
    - maven_build
  needs: ["maven_build"]
